### ISSUE TITLE
Taxonomy group nesting

### ISSUE THREAD

**Issue by petrsvihlik** [Kentico/delivery-sdk-php#37]
The taxonomy models should be hierarchical.

**Comment by dusekdan** [comment]
So after review todos: 
* Unify TaxonomyTerm and Term (only Term should remain)
* Update method commentaries to use `Term array` instead of `array of Term object`
* New default value for `$terms` property of `Term` class should be empty array
* Extend condition in TaxonomyFactory to check not only for empty array, but also for `null` when crafting  nested Terms.

**Comment by petrsvihlik** [comment]
fixed in #46
