### ISSUE TITLE
Implement a retry policy

### ISSUE THREAD

**Issue by JanLenoch** [Kentico/delivery-sdk-php#56]
Add a capability of dealing with transient network outages via the following retry policy:

* The retry policy should be **enabled** by default.
* The following should be configurable (preferably via the `DeliveryOptions` class):
  * enable/disable the retry logic (bool)
  * maximum amount of retry attempts (int)
* If specified, the Delivery client should retry in exponential retry intervals.
* The interval, in milliseconds, is always calculated as a power of the number 2. The exponent is the ordinal number of the next attempt. The result is then multiplied by 100. The order is one-based. For instance, the first retry attempt interval equals to (2<sup>2</sup> * 100), the second equals to (2<sup>3</sup> * 100), etc.
* When all retry attempts fail, the SDK should notify the client code about it, preferable via an exception.

**Comment by JanLenoch** [comment]
Just a note: Platform- or framework-specific conventions have bigger priority than keeping the implementation the same in all our projects. Therefore, the above spec does not have to be followed along strictly, should there be a convention saying otherwise.

**Comment by dusekdan** [comment]
We might bump into maximum execution time limit when user specifies too high number of retry attempts.

If there is a _reliable_ way to figure out maximum execution time for the server on which SDK is running, we could use it to check whether next retry will exceed it and raise a different exception for this specific case, instead of letting server kill it.

**Comment by petrsvihlik** [comment]
@dusekdan that's up to a developer to set the number of attempts appropriately.
