### ISSUE TITLE
SDK timing out on sunra/php-simple-html-dom-parser 

### ISSUE THREAD

**Issue by dusekdan** [Kentico/delivery-sdk-php#60]
I am working on updating Stephenr85's DG sample app to use current SDK version and I have discovered a possible issue in our SDK.

**Steps to reproduce**:
1. Clone [my fork](https://github.com/dusekdan/kentico-cloud-sample-app-php)
2. Run `composer update` and then `php artisan serve`
3. Visit locally started server (probably 127.0.0.1:8000)

The page will be loading for quite some time (approximately 2*t_max-execution_time + 1-2 seconds). After maximum execution time is reached, you will be able to see PHP Fatal error that preceeds the page finally loading:
![image](https://user-images.githubusercontent.com/6360711/40704856-a56b46c6-63e9-11e8-859d-7e3ea7057870.png)

**Comment by Simply007** [comment]
We went through the issue with @dusekdan.

It looks like, it is not a fault of the SDK itself. Maybe it is s combination with [Laravel](https://laravel.com/) or just some application configuration fault.

Sample app is using source sample kentico cloud project (975bf280-fd91-488c-994c-2f04416e5ee3). 

I have tried to run the same code the app is using for loading home page - already in the E2E test `testGetHomeItem` in E2E/DeliveryClientTest.php. And content is loaded without problem.

While debuging the request the simple_html_dom and simple_html_dom_node is descruted multiple times:
*  __destruct().
So @dusekdan tries to extract HtmlDomParser instantiation to the property and use this one instance instead of instantiation the parser all the time, if it helps.

**Comment by dusekdan** [comment]
Extracting `HtmlDomParser` did no good.

What helped, though, was commenting out `__destruct()` method in `simple_html_dom.php` on line 140. 

While this will help me to progress with updating other parts of sample site, it solves nothing and we'll have to get at the bottom of this eventually.

**Comment by petrsvihlik** [comment]
Or a PR? :)

**Comment by dusekdan** [comment]
Further investigation revealed that the issue only occurs when using PHP v7.1.13. We will mention this to DG site's README and recommend not using this version of PHP.

With that, I am closing this issue.

(Relates to #13.)
